### ISSUE TITLE
您好对于您给出的代码复现结果和您的论文提出的结果差别较大，能够提供详细的训练过程日志和数据集的划分方式？

### ISSUE THREAD

**Issue by czjczj** [kexinhuang12345/MolTrans#1]
您好，如题。感谢

**Comment by kexinhuang12345** [comment]
您好 不好意思 没有收到通知。你是哪个dataset 哪个task的结果？我产生一个notebook发你

**Comment by czjczj** [comment]
亲爱的作者您好，MolTrans 论文以及在 Bioinformatics 上 Online了， 能够在github上提供一下完整的数据集（数据集好像不完整）和实验代码，非常感谢。

**Comment by kexinhuang12345** [comment]
好的 可以 我下周之内 更新一下 不好意思 这几周有点过于忙

**Comment by czjczj** [comment]
感谢

**Comment by kexinhuang12345** [comment]
刚刚push了全的dataset，主要的实验，missingness实验和cold drug/protein的实验；code 还有个notebook example； code应该是work的 我只改了那个data path 我过两周会test一下 不过你着急的话可以先用起来
