### ISSUE TITLE
Running MolTrans without GPU

### ISSUE THREAD

**Issue by waqarkaleemkhan** [kexinhuang12345/MolTrans#10]
hi @kexinhuang12345  hope you will be doing well I want to run your code can you please guide how to run it without using GPU because I don't have GPU on my laptop and for information I want to run the train.py file, not the experiment notebook.
Thanks

**Comment by kexinhuang12345** [comment]
Hey, sorry, this model uses transformers and large CNNs, so running on CPU would take forever and are thus highly not recommended. For quick DTI prediction on CPUs, please checkout our DeepPurpose: https://github.com/kexinhuang12345/DeepPurpose
