### ISSUE TITLE
why CUDA error？

### ISSUE THREAD

**Issue by viko-3** [kexinhuang12345/MolTrans#12]
python train.py --task bindingdb

RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1

**Comment by kexinhuang12345** [comment]
it seems to be a cuda issue; not a moltrans issue?

**Comment by viko-3** [comment]
> it seems to be a cuda issue; not a moltrans issue?

what is your cuda version?

**Comment by kexinhuang12345** [comment]
Mine is 10.2

**Comment by kexinhuang12345** [comment]
closing for now
