### ISSUE TITLE
Baseline model implementation

### ISSUE THREAD

**Issue by hyojin0912** [kexinhuang12345/MolTrans#13]
Hello,  I saw your two great paper MolTrans and DeepPurpose.
According to MolTrans you compared MolTrans with DeepConv-DTI, GNN-CPI etc.

These baseline models are implemented in DeepPurpose?
For example, is the DeepConv-DTI model implemented as Drug Encodings=Morgan, Target Encodings=CNN?

If it is right, plz tell me baseline model - Encodings mapping table.
If it is false, could you provide baseline model implementation?

**Comment by kexinhuang12345** [comment]
Hi, the only fully reproduced model is DeepDTA - CNN + CNN. The other should have similar performances if you adjust the hyperparameters in the DeepPurpose (e.g. DeepConv-DTI would be Morgan + CNN). However, in the MolTrans paper, we use the author implementations, which you can find in the original authors provided repo.
