### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 1treu1** [kexinhuang12345/MolTrans#15]
Hello, good morning. Greetings from Colombia! I like the work you have done in MolTrans.
I have some doubts with the datasets:

- In the dataset there is a binary tag, with which the model is trained. This label tells if there is or not an interaction (1. interacts 0. Does not interact). I would like to know where you got this tag from, or what strategy you used for the creation of this binary tag.

- How did you decide the interaction threshold (DTI)? was it deterministic? or a reference you already had? or what strategy did you use?
Regards.

**Comment by kexinhuang12345** [comment]
Hi, you can find all the information in section 3.1 in the paper. https://academic.oup.com/bioinformatics/article/37/6/830/5929692
