### ISSUE TITLE
Running error:(

### ISSUE THREAD

**Issue by xnuohz** [kexinhuang12345/MolTrans#4]
Hi kexin,
I used your code to do regression task on KIBA dataset, and it got `OSError: [Errno 12] Cannot allocate memory`, when I change `num_workers` to 0, it may be ok, but too slow. Is there any other ways to solve this problem?
Thanks:)

**Comment by kexinhuang12345** [comment]
Hi, the kiba dataset is not supported in MolTrans. Are you running your own dataset? It should be okay, since bindingdb is of similar order of size as kiba, and it works fine.
