### ISSUE TITLE
Can change this DTI model into DTA model?

### ISSUE THREAD

**Issue by xuzhang5788** [kexinhuang12345/MolTrans#6]
Thank you for your repo. I think this model can be used as a DTA model if you change the problem from classification to regression. If it is correct, would you like to give us an example? Many thanks

**Comment by kexinhuang12345** [comment]
Hi, yes, that is correct. You may need to change the loss_fct in line 60, 169 to MSE loss and also change the evaluation metrics. You can check out the DeepPurpose repo DTI.py file, as it automatically detects regression vs classification. I will try to change the code later as well to support that.

**Comment by xuzhang5788** [comment]
@kexinhuang12345 
Thank you. I am looking forward to your new implementations soon.

**Comment by DBpackage** [comment]
Hi, I made a fork repository for running Regression with moltrans.
I didn't fixed anything with model.py, adjusted for only predicting in regression tasks.

I hope this helps anybody who wanna get regression results with moltrans.

I appreciate your nice work again! @kexinhuang12345 

https://github.com/DBpackage/MolTrans_DTA

**Comment by kexinhuang12345** [comment]
Great - thank you!
