### ISSUE TITLE
How to convert regression labels of Davis dataset to binary classification labels?

### ISSUE THREAD

**Issue by xueeinstein** [kexinhuang12345/MolTrans#9]
I guess you use a threshold to split the dataset based on the affinity score. How do you choose this threshold? Is there any reference paper to do so?

**Comment by xueeinstein** [comment]
As I know, Davis uses Kd value, how to apply this conversion (Regression label => 0/1) using KIBA score? 
I am not familiar with this area. I really appreciate it if you can help me. Thank you in advance!

**Comment by kexinhuang12345** [comment]
Hi, sorry for the late reply. So, KIBA is designed for different metrics aggregation. We didn't do any KIBA score in the paper. For the Kd, there is no golden threshold.  We take the conservative approach and use 30 uM, as it usually suggests excellent binding affinities. You can also try 10uM, and etc.

**Comment by xueeinstein** [comment]
>We take the conservative approach and use 30 uM, as it usually suggests excellent binding affinities.

Thanks for this useful information!
